<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Wens-MBP" name="HomeAwayInterViewTests" tests="3" failures="1" timestamp="2 Jun 2016 22:50:14 GMT" time="99.294" errors="0">
  <testcase name="testOrderSubmit" time="61.11" classname="qademo.testng.HomeAwayInterviewTest">
    <failure type="java.lang.AssertionError" message="TestCase Failed with exceptions :-1 expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: TestCase Failed with exceptions :-1 expected [false] but found [true]
	at qademo.testng.HomeAwayInterviewTest.testOrderSubmit(Unknown Source)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- testOrderSubmit -->
  <testcase name="testUpdateOrderQuantity" time="29.385" classname="qademo.testng.HomeAwayInterviewTest"/>
  <testcase name="testRemoveAllItemsFromCart" time="8.792" classname="qademo.testng.HomeAwayInterviewTest"/>
</testsuite> <!-- HomeAwayInterViewTests -->
